encryptPassword=false
storePasswordAsHex=false
initialPasswordForAdmin=admin
initialModule=SignIn
modulesHelperProviderClass=com.aptispace.openxava.AptiSpaceModulesHelperProvider
signInHelperProviderClass=com.aptispace.openxava.AptiSpaceSignInHelperProvider
startInLastVisitedModule=false
rememberVisitedModules=false
showModulesMenuWhenNotLogged=false
showApplicationName=true
showOrganizationOnSignIn=false
showListOfOrganizationsOnSignIn=false
updateNaviOXTablesInOrganizationsOnStartup=true


